

export const HELLO_WORLD = 'HELLO_WORLD'
export const SAVE_PERSONAL_INFO = 'SAVE_PERSONAL_INFO'


// Home constants
export const FETCH_FEATURES = 'FETCH_FEATURES'
export const SAVE_HOME_FEATURES = 'SAVE_HOME_FEATURES'
export const DELETE_HOME_FEATURES = 'DELETE_HOME_FEATURES' 
export const FETCH_INITIAL_ITEMS = 'FETCH_INITIAL_ITEMS'
export const MAKE_INITIAL = 'MAKE_INITIAL'


// Cart constants
export const SAVE_TOTAL_CART = 'SAVE_TOTAL_CART'